##The website title
name: Ruixiang Du
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://rdu.im
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "tech_notes/page:num"
##The website description (to be used in meta tags)
description: This is the personal website of Ruixiang Du. This site includes a basic profile of Ruixiang and introductions to his study/research. The site also serves as a personal knowledge base, including technical notes and a wiki. It's aimed at providing convenience of access to knowledge/experience collections for Ruixiang, as well as sharing such information ot others on the Internet.
##Some frequently used keywords on your website
keywords: robotics, embedded, open-source, control, navigation, mobile robot, quadcopter

##define this for disqus comment support
disqus: rxdugit

##set this to enable google analytics
ga_id: UA-47255965-1
ga_domain: rdu.im

##Some commonly used links
links:
  facebook: 
  twitter: 
  email: ruixiang.du@gmail.com
  github: rxdu

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: profile.jpg

##Source and Deploy path
source:      .
destination: ../deploy
