##The website title
name: Ruixiang Du
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
#base_url: http://gituser.github.io (or http://example.com)
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "tech_notes/page:num"
##The website description (to be used in meta tags)
description: Put website description for your home page. (about 50 words or more)
##Some frequently used keywords on your website
keywords: some, relevant, keywords, for, usage, in metatags

##define this for disqus comment support
disqus: rxdugit

##set this to enable google analytics
ga_id: UA-47255965-1
ga_domain: rdu.im

##Some commonly used links
links:
  facebook: 
  twitter: 
  email: ruixiang.du@gmail.com
  github: rxdu

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: profile.jpg

##Source and Deploy path
source:      .
destination: ../deploy
